/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.awt.image.BufferedImage;

/**
 *
 * @author ondra
 */

public class NewJFrame extends javax.swing.JFrame {
    private BufferedImage currentImage = null; // Proměnná pro aktuální obrázek
    private BufferedImage previousImage = null; // Proměnná pro původní obrázek
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setImageButton = new javax.swing.JButton();
        editMatrixButton = new javax.swing.JButton();
        applyMatrixButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        generateImageButton = new javax.swing.JButton();
        restoreOriginalButton = new javax.swing.JButton();
        originalRadioButton = new javax.swing.JRadioButton();
        modifiedRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadImageMenuItem = new javax.swing.JMenuItem();
        saveImageMenuItem = new javax.swing.JMenuItem();
        filtersMenu = new javax.swing.JMenu();
        negativeFilterMenuItem = new javax.swing.JMenuItem();
        pixelizerFilterMenuItem = new javax.swing.JMenuItem();
        identityFilterMenuItem = new javax.swing.JMenuItem();
        tresholdFilterMenuItem = new javax.swing.JMenuItem();
        oldStyleFilterMenuItem = new javax.swing.JMenuItem();
        bwFilterMenuItem = new javax.swing.JMenuItem();
        vinetteFilterMenuItem = new javax.swing.JMenuItem();
        colorizerFilterMenuItem = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setImageButton.setText("Select Image file");
        setImageButton.setMaximumSize(new java.awt.Dimension(120, 25));
        setImageButton.setMinimumSize(new java.awt.Dimension(120, 25));
        setImageButton.setPreferredSize(new java.awt.Dimension(160, 25));
        setImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionLoad(evt);
            }
        });

        editMatrixButton.setText("Edit matrix");
        editMatrixButton.setMaximumSize(new java.awt.Dimension(120, 25));
        editMatrixButton.setMinimumSize(new java.awt.Dimension(120, 25));
        editMatrixButton.setPreferredSize(new java.awt.Dimension(160, 25));
        editMatrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        applyMatrixButton.setText("Apply matrix filter");
        applyMatrixButton.setPreferredSize(new java.awt.Dimension(160, 25));

        generateImageButton.setText("Generate Image");
        generateImageButton.setPreferredSize(new java.awt.Dimension(160, 40));
        generateImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionGenerate(evt);
            }
        });

        restoreOriginalButton.setText("Restore Original Image");
        restoreOriginalButton.setPreferredSize(new java.awt.Dimension(160, 40));
        restoreOriginalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("erasing all changes");
                currentImage = previousImage;
            }
        });

        originalRadioButton.setText("Original Image");
        modifiedRadioButton.setText("Modified Image");

        // Group the buttons
        ButtonGroup group = new ButtonGroup();
        group.add(originalRadioButton);
        group.add(modifiedRadioButton);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        // The "file" menu group
        fileMenu.setText("   File");
        fileMenu.setPreferredSize(new java.awt.Dimension(50, 11));
        fileMenu.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        loadImageMenuItem.setText("Load Image");
        loadImageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionLoad(evt);
            }
        });
        fileMenu.add(loadImageMenuItem);

        saveImageMenuItem.setText("Save Image");
        saveImageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionSave(evt);
            }
        });
        fileMenu.add(saveImageMenuItem);

        jMenuBar1.add(fileMenu);

        // The "filters" menu group
        filtersMenu.setText("Filters");
        filtersMenu.setPreferredSize(new java.awt.Dimension(50, 11));
        filtersMenu.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        negativeFilterMenuItem.setText("negative");
        filtersMenu.add(negativeFilterMenuItem);

        pixelizerFilterMenuItem.setText("Pixelizer");
        filtersMenu.add(pixelizerFilterMenuItem);

        identityFilterMenuItem.setText("identity");
        filtersMenu.add(identityFilterMenuItem);

        tresholdFilterMenuItem.setText("treshold");
        filtersMenu.add(tresholdFilterMenuItem);

        oldStyleFilterMenuItem.setText("OldStyleFilter");
        filtersMenu.add(oldStyleFilterMenuItem);

        bwFilterMenuItem.setText("BW filter");
        filtersMenu.add(bwFilterMenuItem);

        vinetteFilterMenuItem.setText("Vinette");
        filtersMenu.add(vinetteFilterMenuItem);

        colorizerFilterMenuItem.setText("Colorizer");
        filtersMenu.add(colorizerFilterMenuItem);

        jMenuBar1.add(filtersMenu);

        aboutMenu.setText("About");
        aboutMenu.setPreferredSize(new java.awt.Dimension(50, 11));
        aboutMenu.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenuBar1.add(aboutMenu);

        exitMenu.setText("Exit");
        exitMenu.setMaximumSize(new java.awt.Dimension(50, 546444));
        exitMenu.setPreferredSize(new java.awt.Dimension(50, 20));
        exitMenu.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        exitMenu.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jMenuBar1.add(exitMenu);

        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.exit(0);
            }
        });

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editMatrixButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(applyMatrixButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(generateImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restoreOriginalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(originalRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modifiedRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editMatrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(applyMatrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generateImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(restoreOriginalButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(originalRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modifiedRadioButton))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("neoceoceoceo");
        actionLoad(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void actionGenerate(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int resolution = 100;

        BufferedImage generatedImg = new BufferedImage(3 * resolution, 2 * resolution, BufferedImage.TYPE_3BYTE_BGR);

        for (int x = -2 * resolution; x < generatedImg.getWidth() - 2 * resolution; x++){
            for (int y = -resolution; y < generatedImg.getHeight() - resolution; y++){
                float[] z = new float[]{0, 0};
                float[] C = new float[]{(float) x / resolution, (float) y / resolution};

                // (a + bi)^2 = a^2 + 2abi + b^2i^2 = (a˘2-b˘2) + 2abi
                // [a, b] * [a, b] = [a^2 - b^2, 2*a*b]
                // [a, b] * [a, b] + [c, d] =
                // [z[0]*z[0] - z[1]*z[1] + C[0], 2*z[0]*z[1] + C[1]]

                boolean isStable = true;
                for (int i = 0; i < 1000; i++) {
                    float newz0 = z[0]*z[0] - z[1]*z[1] + C[0];
                    float newz1 = 2*z[0]*z[1] + C[1];
                    z[0] = newz0;
                    z[1] = newz1;

                    if (z[0]*z[0] + z[1]*z[1] > 4) {
                        // Point is not in the set
                        isStable = false;
                        generatedImg.setRGB(x + 2 * resolution, y + resolution, (new Color(255, 255, 255).getRGB()));

                        break;
                    }
                }
                if (isStable) {
                    generatedImg.setRGB(x + 2 * resolution, y + resolution, (new Color(0, 0, 0).getRGB()));
                }
            }
        }
        System.out.println("Image done");
        previousImage = currentImage; // Uložení původního obrázku
        this.currentImage = generatedImg;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void actionLoad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser fileChooserLoad = new JFileChooser();
        int returnVal = fileChooserLoad.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooserLoad.getSelectedFile();
            try {
                previousImage = currentImage; // Uložení původního obrázku
                this.currentImage = ImageIO.read(file); // Načtení obrázku

                //printIntoLog("Loaded image: " + file.getName()); // Protokolování
                //redrawPanel(); // Obnovení zobrazení panelu
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error while reading file.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void actionSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser fileChooserSave = new JFileChooser();
        int returnVal = fileChooserSave.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooserSave.getSelectedFile();
            String fileName = file.getAbsolutePath();
            if (!fileName.toLowerCase().endsWith(".jpg")) {
                file = new File(fileName + ".jpg"); // Přidání přípony, pokud chybí
            }
            try {
                ImageIO.write(this.currentImage, "jpeg", file); // Uložení obrázku
                //printIntoLog("Saved image to: " + file.getName()); // Protokolování
                JOptionPane.showMessageDialog(this, "Image saved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error while writing file.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton setImageButton;
    private javax.swing.JButton editMatrixButton;
    private javax.swing.JButton applyMatrixButton;
    private javax.swing.JButton generateImageButton;
    private javax.swing.JButton restoreOriginalButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu filtersMenu;
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem loadImageMenuItem;
    private javax.swing.JMenuItem colorizerFilterMenuItem;
    private javax.swing.JMenuItem saveImageMenuItem;
    private javax.swing.JMenuItem negativeFilterMenuItem;
    private javax.swing.JMenuItem pixelizerFilterMenuItem;
    private javax.swing.JMenuItem identityFilterMenuItem;
    private javax.swing.JMenuItem tresholdFilterMenuItem;
    private javax.swing.JMenuItem oldStyleFilterMenuItem;
    private javax.swing.JMenuItem bwFilterMenuItem;
    private javax.swing.JMenuItem vinetteFilterMenuItem;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton originalRadioButton;
    private javax.swing.JRadioButton modifiedRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
